import { fontConfig } from '@shared/config/fontConfig';

import '@shared/styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fontConfig.className}>{children}</body>
    </html>
  );
}
